apiVersion: v1
kind: Service
metadata:
  labels:
    app: quorum-transaction-signer
    environment: Development
  name: quorum-transaction-signer
  namespace: services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: quorum-transaction-signer
  sessionAffinity: None
  type: ClusterIP
